### ISSUE TITLE
Keyboard usage on site

### ISSUE THREAD

**Issue by ematta** [ericwbailey/empathy-prompts#17]
The site shows:
![image](https://user-images.githubusercontent.com/220164/119868547-c90faa00-bee4-11eb-89d5-4e058d08ddcf.png)
yet I cannot use the keyboard to navigate the site...

**Comment by ericwbailey** [comment]
Thanks for reporting this, @ematta. Are you using Safari by any chance?

**Comment by ematta** [comment]
Firefox, sorry. What other details do you need?

**Comment by ericwbailey** [comment]
You may need to enable full keyboard access for Firefox to support this functionality, see: http://kb.mozillazine.org/Accessibility.tabfocus

This assumes you're using macOS, however.
